<?/*My Father Son relationship: a speech to my Dad on his 70th birthday*/?>
<p><i>On Oct 20 my "Toronto Maple Leaf Fan" father had his 70th birthday and this is the speech I gave.</i></p>

<p>We are here today to celebrate my Dad's 70th birthday.  Until a few years ago I was only able to really understand 1/2 of the father/son relationship.  As a kid you don't take time to cherish the little moments in life, but it's a skill we learn as we get older when it takes more than just a teddy bear to cheer us up.  Now that I have 2 sons I find I am remembering and happily reliving all of the moments that my Dad and I shared together and not a day goes by that I don't think about what you have given me.</p>

<p>Everything I do with Jack and with Noah are things that you took the time necessary and taught me how to do.  When Jack and I play hockey I think about all of the times we went together for hours on end to the local rink when you were first teaching me how to skate and later playing in pickup games.  Every time I play now, I still hear your encouraging voice saying "You can do it, keep skating"!  I know you enjoyed it as much as I did.</p>

<p>All the years I played soccer, I had the best coach there was.  We played so many games and enjoyed so many great moments together from winning championships to simply getting an ice cream at DQ after games.  However, I still think the best coaching move you made each year was always picking me first.</p>

<p>I was 13 when I got my first golf set and was eager to play!  I don't think I am going out on a limb saying golf was never your favourite sport.  However, it quickly became important to you, because it was important to me.  Sure enough shortly after you also got a set of golf clubs for, uh, father's day I think eh...not that I had anything to do with that!  And for anyone who knows my parents, they aren't exactly early risers.  But when you needed to be up for 6 AM hockey practices or an 8 AM tee off time on Saturday morning you were always up early and ready to go with me.</p>

<p>There are too many other sports and clubs that we participated in together to mention them all like softball, beavers, cubs ... You always said, "I am going to be at the games anyway, I might as well get involved!".</p>

<p>Part of being a great leader for me meant you always taught me to make my own decisions and think for myself.  Maybe that's why I put my Leaf days behind me and am now a sens fan!</p>

<p>In 2007 the sens made it to the Stanley Cup...has it really been 4 years already?!?...my company had season tickets and got tickets for the Stanley cup.  I got 2 tickets for game 4 here in Ottawa and I knew who I was taking before I even got the tickets.  We had watched Hockey Night in Canada together so many Saturday nights when I was growing up. It made me very happy and proud that I could take you to a Stanley cup game.  It's something that only comes around a handful of times and to share that with you is something special that I will never forget. It's a good thing I am not a Leaf fan otherwise we wouldn't have ever gotten to go!</p>

<p>Besides sports there were a lot of other things you taught me that I now get to reminisce about.  From building decks and fences, to painting or making a very large and heavy gokart, you gave me the knowledge and seemed to have never ending patience that I am sure I tested on a regular basis.  I remember asking ...ok begging...to help put together some new piece of furniture late on a Saturday night after the hockey game was done, partly because I wanted to stay up, but mostly because I enjoyed spending time with and helping my Dad.  Now my oldest son Jack is oh so eager to help me with whatever is next on my honey to do list.  He is right there with a hammer in one hand and bucket loads of naive energy in the other, and I am proud to be able to pass down to him what you passed down to me.</p>

<p>When done right, the life of a parent never ends and sometimes it just gets multiplied by also being a grandparent.  Recently Amy and I had to persevere through a 3 month stay in the hospital with our youngest son Noah.  We could always count on you and Mom to help with Jack or visit me on the weekends at the hospital, when Amy was taking a rare day off.  There was no prying Noah from Mom so she would usually stay in the room holding Noah and you and I would have lunch in the coffee shop or take a walk outside together.  It was a refreshing change during those long days and I thank you for that.</p>

<p>You have given me big foot steps to follow, but I will do my best at passing down the lessons I have learned to Jack and Noah.  Thank you for your guidance and for being such a great influence throughout my life.  I am very lucky to have you as my father and friend.  On behalf of Amy and Noah, Jack and I wish you a happy 70th birthday and I speak for both of us when I say we embrace the learning and pancakes with syrup still to come.</p>