<?/*A carpenter's house is always the last to get the attention it deserves*/?>
<p>My history in less than 3 tweets.</p>

<p><i>I graduated from computer systems engineering and for 2 years worked at <a href="http://www.lockheedmartin.com/canada/">Lockheed Martin Canada</a> as an embedded C++ developer. Left in late '99 and co-founded <a href="http://www.fuelindustries.com">Fuel Industries</a>. Fast forward about 10 years, 100+ employees, a wife, 2 moves and <strike>1</strike> 2 son's, I made the difficult decision to move on from the typical non-stop roller-coaster ride of a startup.</i></p>

<p>At the time, leaving Lockheed was a big decision, but I don't regret it for a second as Fuel provided invaluable continuous learning that will last with me forever.  It provided me the very <a href="http://www.paulgraham.com/foundersatwork.html">unique experience of building a company</a> from a few employees to working with literally hundreds of great clients, projects and people over that 10 year span.</p>

<p>Awhile ago I read an interesting article that talks about <a href="http://www.smashingmagazine.com/2010/12/28/how-to-maintain-your-personal-brand-as-a-corporate-employee/">your personal profile vs company profile</a>.  It was an interesting read for me since I have been on both sides of the fence.  During that (what seems like a blur looking back) phase my time was usually more valuably spent in the business as there was never any shortage of todo's.  There was just not enough of me left to build and contribute to any form of a personal site - everything was put into the business.  My wife and I <strike>are expecting a 2nd son in March</strike> had our 2nd son this past March and after a few months in hospital with him (a very long story for another time), we are all back home safely.  I figure now is as good a time as any.  I decided to create this site to write, good or bad, to whomever wants to listen (anyone out there??).  I expect there will be a variety of topics including programming, startups, dividend investing, hockey and whatever else floats my boat (did I really just type that??) in the future.</p>

<p>By no means do I think I am a good writer (or fast reader) as I have always been better with numbers than words (thats why I married an english major! :-).  Most of my past writing has been either for proposals or some kind of technical documenation - a topic for another day.  I anticipate this site to be a great channel to practice and maybe receive a little, hopefully constructive, criticism along the way.  Just like most skills, writing requires you to practice to get better and this is a step in the right direction for me.  If I manage to help anyone else along the way then thats all right with me as well.</p>
